name: portfolio
description: "My Personal Portfolio"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  provider: ^6.1.2
  flutter_animate: ^4.5.2
  font_awesome_flutter: ^10.8.0
  google_fonts: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/magdouHealth/
    - assets/images/crewcore/
    - assets/images/ahadith/
    - assets/images/athkar/
    - assets/images/bg/
    - assets/images/icons/
    - assets/images/rozemoon/
    - assets/images/zahra/
    - assets/images/lamha/
    - assets/images/the_closet/
    - assets/images/
    - assets/images/profile/
    - assets/images/fits/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Thin.ttf
          weight: 100
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 300